services:
  kavita:
    image: kizaing/kavita:latest
    container_name: kavita
    hostname: kavita
    environment:
      TZ: "${TZ}"
    volumes:
      - "/opt/homelab/data/kavita:/kavita/config"
      - type: bind
        source: /mnt/storage/media
        target: /media
        read_only: true
        bind:
          create_host_path: false
    ports:
      - "5000:5000"
    restart: unless-stopped
