title: Harw Homelab
description: Private service dashboard
theme: dark
color: violet
headerStyle: clean
statusStyle: dot
target: _blank
disableIndexing: true
hideVersion: true
cardBlur: md
background:
  image: /images/wp0.jpg
  opacity: 55
  saturate: 100
  brightness: 75
layout:
  Infrastructure:
    style: row
    columns: 3
  Main VM:
    style: row
    columns: 4
  Media VM:
    style: row
    columns: 4
